### ISSUE TITLE
Uniprot required column

### ISSUE THREAD

**Issue by tjthurman** [ByrumLab/proteoDA#172]
I wanted to make one sort of "meta-issue" to discuss the various issues related to Uniprot IDs, required columns, etc., so that I make sure everything gets resolved the way we want. Here's my plan:

- [x] For the public pacakge, make uniprot_id a required column column in the annotation, and use the information in that column to also create the rownames for the data and annotation dataframes (instead of using protein123 for the rownames). This will require a check that the information in the uniprot_id column is unique for each row. All these checks will be preformed during DAList creation and validation. This will take care of issue #155, and will also render issue #134 moot.
- [x] Currently, the rownames of the data/annotation data are used as the default for plot titles in the limma report. So, switching to uniprot_id will fix issue #122. I think we should still keep the option to specify a column name used for making the plot title, so that end users can change this if they want. But the default will be uniprot_ID. 
- [ ] For issue #123, about the columns that are displayed in the table of the final report: for the public package we should switch the default to just be uniprot_id (the only required column), with an argument that allows end users to add additional columns if they want. For the internal package, we should set the defaults of this function to be whatever column names we want (currently they're "Gene_name", "Description", and "UniprotID"
